=== jrodriguezh/XML-LenguajeDeMarcas/XML-Lenguajes/biblioteca.dtd
<!ELEMENT biblioteca (libros?,revistas?,periodicos?)>
<!ELEMENT libros (libro*)>
<!ELEMENT libro (titulo,capitulo+,indice_libro,sinopsis)>
<!ATTLIST libro
    referencia ID #REQUIRED
    tipo_clase (novela|infantil|didactico) #REQUIRED
    paginas_libro CDATA #REQUIRED
>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT capitulo (titulo_cap,contenido_libro)>
<!ATTLIST capitulo paginas_cap CDATA #REQUIRED>
<!ELEMENT titulo_cap (#PCDATA)>
<!ELEMENT contenido_libro (#PCDATA)>
<!ELEMENT indice_libro (#PCDATA)>
<!ELEMENT sinopsis (#PCDATA)>

<!ELEMENT revistas (revista)>
<!ELEMENT revista (titulo, numero, indice_revista, seccion_revista)>
<!ATTLIST revista
    id ID #REQUIRED
    tipo_clase (informatica|corazon|coches|investigacion|otras) #REQUIRED
    paginas_rev CDATA #REQUIRED
>
<!ELEMENT titulo_revista (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT indice_revista (#PCDATA)>
<!ELEMENT seccion_revista (contenido_revista)>
<!ATTLIST seccion_revista
    paginas_seccion CDATA #REQUIRED
>
<!ELEMENT contenido_revista (#PCDATA)>

<!ELEMENT periodicos (periodico)>
<!ELEMENT periodico (indice_periodico, seccion_periodico)>
<!ATTLIST periodico
    id ID #REQUIRED
    tipo_clase (nacionales|internacionales) #REQUIRED
    fecha_publicacion CDATA #REQUIRED
>
<!ELEMENT indice_periodico (#PCDATA)>
<!ELEMENT seccion_periodico (articulo)>
<!ATTLIST seccion_periodico
    tipo_seccion (economica|opinion|deportes|nacional|internacional)
<!ELEMENT articulo (contenido_periodico)>
<!ATTLIST articulo
    autor CDATA #REQUIRED
>
<!ELEMENT contenido_periodico (#PCDATA)>

=== jrodriguezh/XML-LenguajeDeMarcas/XML-Lenguajes/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "biblioteca.dtd">

<biblioteca>
    <libros>
        <libro id="L0001" tipo_clase="novela" paginas_libro="177">
            <titulo>El orden del tiempo</titulo>
            <capitulo paginas_cap="50" titulo_cap>
                <contenido_libro>La disgregación del tiempo</contenido_libro>
            </capitulo>
            <capitulo paginas_cap="27">
                <contenido_libro>El mundo sin tiempo</contenido_libro>
            </capitulo>
            <capitulo paginas_cap="100">
                <contenido_libro>Las fuentes del tiempo</contenido_libro>
            </capitulo>
            <indice>
                1. La disgregación del tiempo.
                2. El mundo sin tiempo.
                3. Las fuentes del tiempo.
            </indice>
            <sinopsis>Carlo Rovelli aborda el tiempo y sus enigmas con una combinación única de rigor, capacidad divulfativa y bagaje humanístico.</sinopsis>
        </libro>
    </libros>

    <revistas>
        <revista id="R0001" tipo_clase="informatica" paginas_revista="321">
            <titulo_revista>Byte</titulo_revista>
            <numero>293</numero>
            <indice_revista>
                1. Microservicios, contenedores, dockers y kubernetes.
                2. Centro de datos e hiperconvergencia.
                3. IA en las Administraciones.
            </indice_periodico>
            <seccion_revista paginas_seccion="71">
                <contenido>Microservicios, contenedores, dockers y kubernetes.</contenido_revista>
            </seccion_revista>
            <seccion_revista paginas_seccion="200">
                <contenido_revista>Centro de datos e hiperconvergencia.</contenido_revista>
            </seccion_revista>
            <seccion_revista paginas_seccion="50">
                <contenido_revista>IA en las Administraciones.</contenido_revista>
            </seccion_revista>
        </revista>
    </revistas>

    <periodicos>
        <periodico id="P0001" tipo_clase="nacional" fecha_publicacion="18-05-2021">
            <indice_periodico>
                1. Madrid celebra el Día de los Museos.
                2. La historia de superación de la pequeña Naiara.
                3. La Jean-Luc Godard Street Band presenta disco.
                4. VIII Campamento Deportivo Urbano de Verano.
                5. Así ha votado Carabanchel en las elecciones a la Comunidad de Madrid.
            </indice_periodico>
            <seccion_revista tipo_seccion="opinion">
                <articulo autor="Jesús Perez">
                    <contenido_periodico>Madrid celebra el Día de los Museos</contenido_periodico>
                </articulo>
            </seccion_revista>
            <seccion_revista tipo_seccion="nacional">
                <articulo autor="José Luis Marquez">
                    <contenido_periodico>La historia de superación de la pequeña Naiara</contenido_periodico>
                </articulo>
            </seccion_revista>
        </periodico>
    </periodicos>

</biblioteca>
