=== jrodriguezh/XML-LenguajeDeMarcas/biblioteca.dtd
<!ELEMENT biblioteca (libro*, revista*, periodico*)>

<!-- Parte relativa a libro. Ya que algunos elementos serán comunes a los otros elementos tambíen se definen aquí-->

<!ELEMENT libro (titulo, indice, sinopsis, capitulo+)>
<!ATTLIST libro id ID #REQUIRED>
<!ATTLIST libro n_paginas CDATA #REQUIRED>
<!ATTLIST libro tipo_clase (novela | infantil | didactico) #REQUIRED>

<!ELEMENT titulo (#PCDATA)>
<!ELEMENT capitulo (titulo, contenido)>
<!ATTLIST capitulo n_paginas CDATA #REQUIRED>


<!ELEMENT contenido (#PCDATA)>
<!ENTITY contenidocapitulo1 "Url del contenido de capítulo1">
<!ENTITY contenidocapitulo2 SYSTEM "Url del contenido de capitulo2">

<!ELEMENT indice (#PCDATA)>
<!ELEMENT sinopsis (#PCDATA)>



<!-- Parte relativa a revista-->

<!ELEMENT revista (numero, titulo, indice, seccion+)>
<!ATTLIST revista id ID #REQUIRED>
<!ATTLIST revista tipo_clase (informatica | corazon | coches | investigacion | otros) #REQUIRED>

<!ELEMENT numero (#PCDATA)>
<!ELEMENT seccion (contenido)>
<!ATTLIST seccion n_paginas CDATA #REQUIRED>

<!ENTITY contenidorevista SYSTEM "URL del contenido de la revista">



<!--Parte relativa al periodico-->



<!ELEMENT periodico (seccion_per+, indice)>
<!ATTLIST periodico id ID #REQUIRED>
<!ATTLIST periodico tipo_clase CDATA #REQUIRED>
<!ATTLIST periodico fecha_pub CDATA #REQUIRED>  


<!ELEMENT seccion_per (articulo+)>
<!ATTLIST seccion_per tipo (economia | opinion | deportes | nacional | internacional) #REQUIRED>

<!ELEMENT articulo (contenido)>
<!ATTLIST articulo autor_art CDATA #REQUIRED>

<!ENTITY contenidoarticulo SYSTEM "Url del articulo referido">

=== jrodriguezh/XML-LenguajeDeMarcas/Requerimiento1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE biblioteca SYSTEM "biblioteca.dtd">
<biblioteca>
    <libro id="L0001" n_paginas="435" tipo_clase="novela">
        <titulo>Titulo de libro</titulo>
        <indice>Índice</indice>
        <sinopsis>Sinopsis del libro</sinopsis>
        <capitulo n_paginas="35">
            <titulo>Título capítulo 1</titulo>
            <contenido>&contenidocapitulo1; </contenido>
        </capitulo>
        <capitulo n_paginas="400">
            <titulo>Título capítulo 2</titulo>
            <contenido>&contenidocapitulo2;</contenido>
        </capitulo>
    </libro>
    <revista id="R0010" tipo_clase="informatica">
        <numero>Número de la revista</numero>
        <titulo>Título de la revista</titulo>
        <indice>Índice de la revista</indice>
        <seccion n_paginas="15">
            <contenido>&contenidorevista;</contenido>
        </seccion>

    </revista>

    <periodico id="P0001" tipo_clase="nacional" fecha_pub="07/05/11">
        <seccion_per tipo="economia">
            <articulo autor_art="Pepe perez">
                <contenido>&contenidoarticulo;</contenido>
            </articulo>
        </seccion_per>
        <indice>Índice del periódico</indice>
    </periodico>
</biblioteca>
